FROM python:3.10-slim
WORKDIR /lab3
COPY index_calculus.py .
CMD ["python", "index_calculus.py"]
Pull docker image
docker pull cryptolom\index-calculus:latest
Run docker image
docker run --rm -it cryptolom\index-calculus:latest
